SERVER_PORT: 8080

PORT_DB: 5480
POSTGRES_SCHEMA: public
POSTGRESQL_DATABASE: fields
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: postgres
POSTGRES_HOST: localhost

METEO_PORT: 8003
METEO_HOST: localhost
